Course.dashboard/Controllers/API/ProfileUsersController.cs
using Course.Service.IServices;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Course.dashboard.Controllers.API {
    [Route("api/[controller]/[action]")]
    [ApiController]
    public class ProfileUsersController : ControllerBase {
        private readonly IAccountService _service;

        public ProfileUsersController(IAccountService accountService)
        {
            _service = accountService;
        }

        [HttpGet]
        [AllowAnonymous]
        public IActionResult Profile(string email)
        {
            var result = _service.ProfileUser(email);
            if (result == null)
            {
                return NotFound(new { Data = result, Message = "Your Request Falied" });
            }
            return Ok(new { Data = result, Message = "Done" });
        }
        [HttpPost]
        public IActionResult UpdateUserNameAndPhoto(string email, string username, IFormFile userphoto)
        {
            if (_service.UpdateUserInfo(userphoto, username, email).Result)
            {

                return Ok(new { Message = "Done" });
            }

            return NotFound(new { Message = "Your Request Falied" });
        }
        [HttpPost]
        public IActionResult UpdateUserSocial(string Facebook, string Twitter, string Instagram, string linkedin, string email)
        {

            if (_service.UpdateUserSocial(Facebook, Twitter, Instagram,linkedin, email).Result)
            {

                return Ok(new { Message = "Done" });
            }

            return NotFound(new { Message = "Your Request Falied" });
        }
        [HttpPost]
        public IActionResult UpdateUserAbout(string about, string email)
        {
            if (_service.UpdateUserAbout(about, email).Result)
            {
                return Ok(new { Message = "Done" });
            }
            return NotFound(new { Message = "Your Request Falied" });
        }
    }
}

Course.dashboard/Controllers/MVC/ProfileUserController.cs
using Course.Service.IServices;
using Microsoft.AspNetCore.Mvc;
using NToastNotify;

namespace Course.dashboard.Controllers.MVC {
    public class ProfileUserController : Controller {
        private readonly IAccountService _service;
        private readonly IToastNotification _toast;

        public ProfileUserController(IAccountService service, IToastNotification toast)
        {
            _service = service;
            _toast = toast;
        }
        [HttpGet]
        public IActionResult Profile(string email)
        {
            var result=_service.ProfileUser(email).Result;
            return View(result);
        }
        [HttpPost]
        public IActionResult UpdateUserNameAndPhoto(string email,string username,IFormFile userphoto)
        {
           if( _service.UpdateUserInfo(userphoto,username, email).Result)
            {
                _toast.AddSuccessToastMessage("Completed Change");
                return RedirectToAction(nameof(Profile), new { email = email });
            }
            _toast.AddErrorToastMessage("Failed Change");
            return RedirectToAction(nameof(Profile), new { email = email });
        }
        [HttpPost]
        public IActionResult UpdateUserSocial(string Facebook, string Twitter,string Instagram,string LinkediN,string email)
        {

            if (_service.UpdateUserSocial(Facebook,Twitter,Instagram,LinkediN,email).Result)
            {
                _toast.AddSuccessToastMessage("Completed Change");
                return RedirectToAction(nameof(Profile), new { email = email });
            }
            _toast.AddErrorToastMessage("Failed Change");
            return RedirectToAction(nameof(Profile), new { email = email });
        }
        [HttpPost]
        public IActionResult UpdateUserAbout(string about,string email)
        {
            if (_service.UpdateUserAbout(about,email).Result)
            {
                _toast.AddSuccessToastMessage("Completed Change");
                return RedirectToAction(nameof(Profile), new { email = email });
            }
            _toast.AddErrorToastMessage("Failed Change");
            return RedirectToAction(nameof(Profile), new { email = email });
        }
    }
}

Course.dashboard/Views/ProfileUser/Profile.cshtml
@model ProfileUserViewModel;
@{
    ViewData["Title"] = "Profile";
}
<section class="Profie">
    <!--Test If Object Is null-->
    @if (Model != null)
    {
        <!--Image-->
        <div class="roles row">
            <div class="user-photo col-md-12 text-center">
                <div style="width:20%;height:20%;margin: auto;">
                @if (String.IsNullOrEmpty(Model.img))
                {
                        <img src="~/~/UI/images/Profile/Profile.png" class="img-thumbnail img-fluid rounded" alt="@Model.Name" />
                }
                else
                {
                        <img src="~/~/UI/images/Profile/@Model.img" class="img-thumbnail img-fluid rounded" alt="@Model.Name" />
                }
                @if (String.IsNullOrEmpty(Model.Name))
                {
                    <h4 class="name">Your Name</h4>
                }
                else
                {
                    <p class="name">@Model.Name</p>
                    }
                </div>
                <i data-toggle="modal" data-target="#Photo" class="bi bi-pencil-square"></i>
            </div>
        </div>
        <div class="row roles user-media">
            <div class="user-socialmedia">
                <a href="@Model.Facebook" target="_blank"><i class="bi bi-facebook"></i></a>
                <a href="@Model.Twitter" target="_blank"><i class="bi bi-twitter"></i></a>
                <a href="@Model.Instagram" target=" _blank"><i class="bi bi-instagram"></i></a>
                <a href="@Model.LinkedIn" target=" _blank"><i class="bi bi-linkedin"></i></a>
            </div>
            <i data-toggle="modal" data-target="#Social" class="bi bi-pencil-square"></i>
        </div>
        <div class="row roles about-user">
            @if (string.IsNullOrEmpty(Model.About))
            {
                <p class="about">Tell Us About YourSelf</p>
            }
            else
            {
                <p class="about">@Model.About</p>
            }
            <i data-toggle="modal" data-target="#About" class="bi bi-pencil-square"></i>
        </div>
    }
</section>
 <!--Popup for Photo and Name-->
<div id="Photo" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title text-center">Enter Name and Photo </h4>
            </div>
            <div class="modal-body">
                <form method="post" asp-action="UpdateUserNameAndPhoto" asp-controller="ProfileUser" asp-route-email="@User.Identity.Name" enctype="multipart/form-data">
                    <div asp-validation-summary="ModelOnly"></div>
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="Name" id="Name" name="username" required="" />
                    </div>
                    <div class="form-group">
                        <input type="file" class="form-control" placeholder="Your Image" id="photo" name="userphoto" required="" />
                    </div>
                    <div class="form-group">
                        <input type="submit" class="btn btn-primary" value="Update" style="background-color: #006df0" />
                    </div>
               </form>
            </div>
        </div>
    </div>
</div>

<!--Popup for Social Media-->
<div id="Social" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title text-center">Social Media</h4>
            </div>
            <div class="modal-body">
                <form method="post" asp-action="UpdateUserSocial" asp-controller="ProfileUser" asp-route-email="@User.Identity.Name">
                    <div asp-validation-summary="ModelOnly"></div>
                    <div class="form-group">
                        <input type="url" class="form-control" placeholder="Facebook" id="Facebook" name="Facebook" required="" />
                    </div>
                    <div class="form-group">
                        <input type="url" class="form-control" placeholder="Twitter" id="Twitter" name="Twitter" required="" />
                    </div>
                    <div class="form-group">
                        <input type="url" class="form-control" placeholder="Instagram" id="Instagram" name="Instagram" required="" />
                    </div>  
                    <div class="form-group">
                        <input type="url" class="form-control" placeholder="LinkedIn" id="LinkedIn" name="LinkedIn" required="" />
                    </div>
                    <div class="form-group">
                        <input type="submit" class="btn btn-primary" value="Update" style="background-color: #006df0" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<!--Popup for Tell Us About your Self-->
<div id="About" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title text-center">About </h4>
            </div>
            <div class="modal-body">
                <form method="post" asp-action="UpdateUserAbout" asp-controller="ProfileUser" asp-route-email="@User.Identity.Name">
                    <div asp-validation-summary="ModelOnly"></div>
                    <div class="form-group">
                        <textarea class="form-control" cols="12" rows="12" name="about" placeholder="About you ...."></textarea>
                    </div>
                    <div class="form-group">
                        <input type="submit" class="btn btn-primary" value="Update" style="background-color: #006df0" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>