Course.dashboard/Controllers/MVC/ContactUsController.cs
using Course.Service.IServices;
using Microsoft.AspNetCore.Mvc;
using NToastNotify;

namespace Course.dashboard.Controllers.MVC {
    public class ContactUsController : Controller {
        private readonly IContactService _contactService;
        private readonly IToastNotification _toast;
        public ContactUsController(IContactService contactService, IToastNotification toast)
        {
            _contactService = contactService;
            _toast = toast;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _contactService.GetContactUsAsync());
        }
        [HttpGet]
        public async Task<IActionResult> Delete(int Id)
        {
            if (!await _contactService.Delete(Id)) 
            {
                _toast.AddErrorToastMessage("Falied");
                return RedirectToAction(nameof(Index));
            }
            _toast.AddSuccessToastMessage("Done");
            return RedirectToAction(nameof(Index));
        }
    }
}

Course.dashboard/Views/ContactUs/Index.cshtml
@model IEnumerable<ContactUsViewModel>
@{
    ViewData["Title"] = "Messages";
}

<section class="roles">
    <div class="row">
        <div class="col-md-12">
            <h1> Conatct us From Clients </h1>
        </div>
        <div class="col-md-10" style="margin-top:20px">
            <table class="table table-hover table-striped" id="table">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Message</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                     @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.Name</td>
                            <td>@item.Email</td>
                            <td>@item.Message</td>
                            <td>
@*                                <a class="btn btn-primary" asp-controller="Contact" asp-action="Delete"><i class="bi bi-check2"></i></a>
*@
                                <a class="btn btn-danger" asp-controller="ContactUs" asp-action="Delete" asp-route-Id="@item.Id"><i class='bi bi-trash3-fill'></i></a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</section>

@section Scripts{
    <Partial name="_ValidationScriptsPartial" />
}