Course.dashboard/Controllers/API/AdmistrationsController.cs
using Course.Repository.ViewModeles;
using Course.Service.IServices;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Course.dashboard.Controllers.API {
    [Route("api/[controller]/[action]")]
    [ApiController]
    public class AdmistrationsController : ControllerBase {
        private readonly IAccountService _accountService;

        public AdmistrationsController(IAccountService accountService)
        {
            _accountService = accountService;
        }
        [HttpGet]
        [AllowAnonymous]
        public IActionResult Roles()
        {
            var data = _accountService.GetRoles().Result;
            return Ok(new {Data=data,Message="Successfully Request"});
        }
        [HttpPost]
        [AllowAnonymous]
        public IActionResult AddRole(string Name)
        {
            var result = _accountService.AddRole(Name).Result;
            if (result is null)
            {
                return Ok(new { Data = string.Empty, Message = "Falied Your Request" });
            }
            return Ok(new { Data = result, Message = "Done" });
        }
        [HttpDelete]
        [AllowAnonymous]
        public IActionResult DeleteRole(string Id)
        {
            var result = _accountService.DeleteRole(Id).Result;
            if (result is null)
            {
                return Ok(new { Data = string.Empty, Message = "Falied Your Request" });
            }
            return Ok(new { Data = result, Message = "Done" });
        }
        [HttpPut]
        [AllowAnonymous]
        public IActionResult EditRole(string Id,string roleName)
        {
            if(_accountService.UpdateRole(Id,roleName).Result != null)
            {
                return Ok(new { Data = new { Id = Id, Name = roleName }, Message = "Success Update" });
            }
            return Ok(new { Data = string.Empty, Message = "Falied Your Request" });
        }
        [HttpPost]
        [AllowAnonymous]
        public IActionResult EditUserRole(UsersInRoleViewModel model)
        {
            if (model is null || !model.UsersInfo.Any())
            {
                return Ok(new { Data = String.Empty, Message = "Try Again" });
            }

            if (_accountService.UpdateUsersInRole(model).Result)
            {
                return Ok(new { Data = model, Message = "Success Update" });
            }
            return Ok(new { Data = string.Empty, Message = "Falied Your Request" });
        }
    }
}

Course.dashboard/Controllers/MVC/AdmistrationController.cs
using Course.Repository.ViewModeles;
using Course.Service.IServices;
using Microsoft.AspNetCore.Mvc;
using NToastNotify;

namespace Course.dashboard.Controllers.MVC {
    public class AdmistrationController : Controller {
        private readonly IAccountService _accountService;
        private readonly IToastNotification _toast;

        public AdmistrationController(IAccountService accountService, IToastNotification toast)
        {
            _accountService = accountService;
            _toast = toast;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public JsonResult Roles()
        {
            var data = _accountService.GetRoles().Result;
            return Json(data);
        }
        [HttpGet]
        
        public JsonResult AddRole(string Name)
        {
            if(! (_accountService.AddRole(Name).Result is null)) {   
                
                return Json("ok");
            }
            return Json("no");
        }
        [HttpGet]
        public JsonResult DeleteRole(string Id)
        {
            if (String.IsNullOrEmpty(Id))
            {
                return Json("no");
            }
            var result=_accountService.DeleteRole(Id).Result;
            if(result is null)
            {
               return Json("no");
            }
            return Json("ok");
        }
        [HttpGet]
        public ActionResult EditRole(string Id)
        {
            var role = _accountService.GetRoleById(Id).Result;
            var usersinRole = _accountService.UserInRole(role.Name).Result;
            EditRoleViewModel model = new EditRoleViewModel()
            {
                role = role,
                UserName = usersinRole
            };
            return View(model);
        }
        [HttpPost]
        public IActionResult EditRole(string Id,string Name)
        {
            if(_accountService.UpdateRole(Id,Name).Result is null)
            {
                _toast.AddErrorToastMessage("Failed Update");
                return RedirectToAction(nameof(EditRole),new {Id=Id });
            }
            _toast.AddSuccessToastMessage("Completed Change");
            return RedirectToAction(nameof(Index));
        }
        [HttpGet]
        public IActionResult EditUserRole(string roleId)
        {
            var role = _accountService.GetRoleById(roleId).Result;
            var usersInRole=_accountService.UsersInRole(role.Name).Result;
            if(role==null || usersInRole == null)
            {
                return RedirectToAction(nameof(Index));
            }
            UsersInRoleViewModel usersInRoleView = new UsersInRoleViewModel()
            {
                role = role,
                UsersInfo = usersInRole
            };

            return View(usersInRoleView);
        }
        [HttpPost]
        public IActionResult EditUserRole(UsersInRoleViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (_accountService.UpdateUsersInRole(model).Result)
                {
                    return RedirectToAction(nameof(EditRole), new { Id = model.role.Id });
                }
            }
            ModelState.AddModelError(String.Empty, "Something Happing");
            return View();
        }
    }
}

Course.dashboard/Views/Admistration/EditRole.cshtml
@model EditRoleViewModel;
@{
    ViewData["Title"] = "Update Role";
}
<section>
    <div class="row roles">
        <div class="col-md-12">
            @if (Model.role != null)
            {
                <form asp-controller="Admistration" asp-action="EditRole" asp-route-Id="@Model.role.Id" class="form-horizontal">
                 <div asp-validation-summary="ModelOnly"></div>
                    <div class="form-group">
                        <label asp-for="@Model.role.Id" class="control-label col-sm-2"></label>
                        <div class="col-sm-10">
                            <input disabled asp-for="@Model.role.Id" name="Id" class="form-control">
                            <span asp-validation-for="@Model.role.Id"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label asp-for="@Model.role.Name" class="control-label col-sm-2"></label>
                        <div class="col-sm-10">
                            <input asp-for="@Model.role.Name" name="Name" class="form-control">
                            <span asp-validation-for="@Model.role.Name"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <input type="submit" value="Update" class="btn btn-primary" style="background-color: #006df0" />
                            <a asp-area="" asp-controller="Admistration" asp-action="Index" class="btn btn-danger">Cancel</a>
                        </div>
                    </div>
                </form>
            }
            else
            {
                <div class="card">
                    <div class="card-body">
                        <h3 class="card-text">Not Avaliable Update Role at Moment</h3>
                     
                        <a asp-area="" asp-controller="Admistration" asp-action="Index" class="btn btn-danger" class="card-link">Cancel</a>
                    </div>
                </div>
            }
        </div>
    </div>
</section>
<section>
    <div class="row" style="display:flex;justify-content:center;margin-top:5px">
        @if (Model.role != null && Model.UserName.Any())
        {
            <div class=" col-md-6 card roles" style="margin:5px">
                <div class="card-body">
                    <h5 class="card-title">@Model.role.Name</h5>
                    @foreach (var user in Model.UserName.ToList())
                    {
                        <p class="card-text">@user</p>
                    }
                    <a asp-controller="Admistration" asp-action="EditUserRole" asp-route-roleId="@Model.role.Id" class="btn btn-primary card-link" style="background-color: #006df0">Edit</a>
                    <a asp-area="" asp-controller="Admistration" asp-action="Index" class="btn btn-danger" class="card-link">Cancel</a>
                </div>
            </div>
        }
        else
        {
            <div class=" col-md-4 card roles">
                <div class="card-body">
                    <h5 class="card-title">@Model.role.Name</h5>
                    <p class="card-text">Not Valiable User at Moment</p>
                    <a asp-area="" asp-controller="Admistration" asp-action="EditUserRole" asp-route-roleId="@Model.role.Id" class="btn btn-primary" style="background-color: #006df0" class="card-link">Edit</a>
                    <a asp-area="" asp-controller="Admistration" asp-action="Index" class="btn btn-danger" class="card-link">Cancel</a>
                </div>
            </div>
        }
    </div>
</section>
@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}

Course.dashboard/Views/Admistration/EditUserRole.cshtml
@model UsersInRoleViewModel;
@{
    ViewData["Title"] = "Edit Users Role";
}
@if (Model is null)
{
    <div class="card roles">
        <div class="card-body">
            <h3 class="card-text">Not Avaliable Update Role at Moment</h3>

            <a asp-area="" asp-controller="Admistration" asp-action="Index" class="btn btn-danger" class="card-link">Cancel</a>
        </div>
    </div>
}
else
{
    <div class="card roles">
        <div class="card-body">
            <h3 class="card-text">@Model.role.Name</h3>
            <form method="post" asp-action="EditUserRole" asp-controller="Admistration" style="margin-top:20px">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div>
                    <input asp-for="@Model.role.Id" hidden />
                    <input asp-for="@Model.role.Name" hidden />
                </div>
                @if (Model.UsersInfo.Any())
                {
                    for (int i = 0; i < Model.UsersInfo.Count; i++)
                    {
                        <div class="form-group">
                            <input asp-for="@Model.UsersInfo[i].UserName" hidden />
                            <input asp-for="@Model.UsersInfo[i].UserId" hidden />
                        </div>
                        <div class="form-check" style="margin-top:5px">
                            <input class="form-check-input" type="checkbox" asp-for="@Model.UsersInfo[i].IsSelected" id="defaultCheck1" />
                            <label asp-for="@Model.UsersInfo[i].UserName" class="form-check-label" for="defaultCheck1">
                                @Model.UsersInfo[i].UserName
                            </label>
                        </div>
                    }
                    <div class="form-group" style="margin-top:20px">
                        <input type="submit" value="Edit" class="btn btn-primary" style="background-color: #006df0" />
                        <a asp-area="" asp-controller="Admistration" asp-action="Index" class="btn btn-danger" class="card-link">Cancel</a>
                    </div>
                }
            </form>
        </div>
    </div>
}
@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}

Course.dashboard/Views/Admistration/Index.cshtml
@{
    ViewData["Title"] = "Roles";
}
<style>
    #newrole {
        display: none;
        color: red;
    }
</style>
<section class="roles">
    <div class="row">
        <div class="col-md-12">
            <div><a data-toggle="modal" data-target="#myModal" class="btn btn-primary" style="background-color: #006df0"><i class="bi bi-plus"></i>New Role</a></div>
        </div>
        <div class="col-md-10" style="margin-top:20px">
            <table class="table table-hover" id="table">
                <thead>
                    <tr>
                        <th>Code</th>
                        <th>Name</th>
                        <th></th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
</section>
<!-------------Popup Add Role---------------->
<div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" style="text-align: center;">New Role</h4>
            </div>
            <div class="modal-body">
                <form id="sub">
                    <div class="form-group">
                        <label for="role">Name</label>
                        <input type="text" class="form-control" placeholder="Role Name" id="role">
                        <span id="newrole">Required Name</span>
                    </div>
                    <div class="form-group pupo">
                        <input type="submit" value="Add" style="background-color: #006df0" class="btn btn-primary" />
                        <button type="button" id="close" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>
                </form>
            </div>
        </div>

    </div>
</div>
@section Scripts{
    <script>
        $(document).ready(function () {
            $("#table").dataTable({
                "ajax": {
                    "url": "/Admistration/Roles",
                    "type": "GET",
                    "dataSrc": "",
                    "datatype": "json"
                },
                "columnDefs": [{
                    "targets": 2,
                    "orderable": false
                }],
                "columns": [
                    { "data": "code", "autoWidth": true },
                    { "data": 'name', "autoWidth": true },
                    { "render": function (data, type, full) { return "<a  class='btn btn-danger' onclick=DeleteRole('" + full.code + "') ><i class='bi bi-trash3-fill'></i></a> <a  href='/Admistration/EditRole/"+full.code+"' class='btn btn-primary'><i class='bi bi-pencil-square'></i></a>" } }
                ]
            });
        })
        function DeleteRole(id){
            $.ajax({
                url: '/Admistration/DeleteRole?Id=' + id,
                type: "GET",
                contentType: "application/json; charset=utf-8",
                success: function (data) {
                    if (data == 'ok') {
                        toastr.success('Success ');

                    } else {
                        toastr.error('Errors ');
                    }
                    setTimeout(function () {
                        window.location = '/Admistration/Index'
                    }, 500)
                },
            })
        }
        document.getElementById('sub').addEventListener("submit", function (e) {
            debugger
            e.preventDefault();
            if (ValidtionForm()) {
                var name = document.getElementById('role').value;
                $.ajax({
                    url: '/Admistration/AddRole?Name=' + name,
                    type: "GET",
                    contentType: "application/json; charset=utf-8",
                    success: function (data) {
                        if (data == 'ok') {
                            toastr.success('Success ');  
                       
                        } else {
                            toastr.error('Errors ');
                        }
                        $("#close").click();
                       setTimeout(function(){
                            window.location = '/Admistration/Index'
                        },1000)
                    },
                })
            } else {
                console.log(false);
            }
        });
        function ValidtionForm() {
            debugger
            var name = document.getElementById('role').value;
            var required = document.getElementById('newrole');
            if (name == "" || name == undefined || name == null) {
                required.style.display = "block"
                return false;
            } else {
                required.style.display = "none"
                return true;
            }
        }
        document.getElementById('role').onkeyup = function () {
            ValidtionForm();
        }

    </script>
    }