Course.dashboard/Areas/UI/Controllers/AuthController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NToastNotify;

namespace Course.dashboard.Areas.UI.Controllers {
	[Area("UI")]
	public class AuthController : Microsoft.AspNetCore.Mvc.Controller {
		private readonly IAuthRepository _authRepository;
		private readonly IHttpContextAccessor _httpContextAccessor;
		private readonly IToastNotification _toast;
		public AuthController(IAuthRepository authRepository, IToastNotification toast, IHttpContextAccessor httpContextAccessor)
		{
			_authRepository = authRepository;
			_toast = toast;
			_httpContextAccessor = httpContextAccessor;
		}

		[AllowAnonymous]
		[HttpGet]
		public IActionResult Register()
		{
			return View();
		}
		[HttpPost]
		[ValidateAntiForgeryToken]
		[AllowAnonymous]
		public async Task<IActionResult> Register(RegisterViewModel model)
		{
			if (!ModelState.IsValid || !await _authRepository.RegisterUI(model))
			{
				ModelState.AddModelError(string.Empty, "incorrect Password or email");
				_toast.AddErrorToastMessage("incorrect Password or email");
				return View();
			}
			_httpContextAccessor.HttpContext?.Response.Cookies.Append("UName", model.Username);
			return RedirectToAction(nameof(Index), "Home");
		}

		[HttpGet]
		[AllowAnonymous]
		public IActionResult Login()
		{
			return View();
		}
		[HttpPost]
		[AllowAnonymous]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Login(LoginViewModel model)
		{
			if (!ModelState.IsValid)
			{
				ModelState.AddModelError(string.Empty, "incorrect Password or email");
				_toast.AddErrorToastMessage("incorrect Password or email");
				return View();

			}
			var path = await _authRepository.Login(model);
			if (path == "user")
				return RedirectToAction(nameof(Index), "Home");
			return Redirect("~/" + path);
		}
		[HttpGet]
		[AllowAnonymous]
		public IActionResult ContactUs()
		{
			return View();
		}
		[HttpPost]
		[AllowAnonymous]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> ContactUs(ContactUsViewModel model)
		{
			if (!ModelState.IsValid ||! await _authRepository.Contactus(model))
			{
				ModelState.AddModelError(string.Empty, "Ivalid Data");
				_toast.AddAlertToastMessage("Try again");
				return View();
			}
			_toast.AddSuccessToastMessage("Done");
			return RedirectToAction(nameof(Index), "Home");
		}
		[AllowAnonymous]
		[HttpGet]
		public async Task<IActionResult> LogOut()
		{
			await _authRepository.LogOut();
			_httpContextAccessor.HttpContext?.Response.Cookies.Delete("UName");
			return RedirectToAction(nameof(Register));
		}
	}
}

Course.dashboard/Areas/UI/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using NToastNotify;
using System.Drawing.Printing;

namespace Course.dashboard.Areas.UI.Controllers {
    [Area("UI")]
    public class CartController : Microsoft.AspNetCore.Mvc.Controller {
        private readonly ICartRepository _cartRepository;
        private readonly IToastNotification _toast;
        private readonly IHttpContextAccessor _httpContextAccessor;
        public CartController(ICartRepository cartRepository, IToastNotification toast, IHttpContextAccessor httpContextAccessor)
        {
            _cartRepository = cartRepository;
            _toast = toast;
            _httpContextAccessor = httpContextAccessor;
        }
        [HttpGet]
        public async Task<IActionResult> Add(int Id, string uname, string returnUrl, string type)
        {
            if (await _cartRepository.Add(Id, uname, type))
            {
                _toast.AddSuccessToastMessage("Add To Cart ");
                return LocalRedirect(returnUrl);
            }
            _toast.AddErrorToastMessage("Falied To Add");
            return LocalRedirect(returnUrl);
        }
        [HttpGet]
        public async Task<IActionResult> Checkout(int currentPage, decimal discound, string uname, int pagesize)
        {
            _toast.AddSuccessToastMessage("Done ");
            uname = uname ?? _httpContextAccessor.HttpContext?.Request.Cookies["UName"];
            return View(await _cartRepository.Checkout(uname, currentPage, pagesize, discound));
        }
        [HttpGet]
        public async Task<IActionResult> Delete(int Id, string UN)
        {
            if (Id <= 0 || String.IsNullOrEmpty(UN) || !await _cartRepository.DeleteCart(Id, UN))
            {
                _toast.AddErrorToastMessage("UnCorrect");
                return RedirectToAction(nameof(Checkout), new { currentPage = 1, discound = 0.1, uname = UN, pagesize = 4 });
            }
            _toast.AddSuccessToastMessage("Done ");
            return RedirectToAction(nameof(Checkout), new { currentPage = 1, discound = 0.1, uname = UN, pagesize = 4 });
        }
    }
}

Course.dashboard/Areas/UI/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NToastNotify;

namespace Course.dashboard.Areas.UI.Controllers {
    [Area("UI")]
    public class HomeController : Microsoft.AspNetCore.Mvc.Controller {
        private readonly IAuthRepository _authRepository;
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly IToastNotification _toast;
        public HomeController(IAuthRepository authRepository, IToastNotification toast, IHttpContextAccessor httpContextAccessor)
        {
            _authRepository = authRepository;
            _toast = toast;
            _httpContextAccessor = httpContextAccessor;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            return View(await _authRepository.IndexRepo());
        }
        [HttpGet]
        public async Task<IActionResult> AboutUs()
        {
            return View(await _authRepository.AboutUsRepo());
        }
    }
}

Course.dashboard/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Course.dashboard.Controllers {
    public class HomeController : Controller {
        [AllowAnonymous]
        public IActionResult Index()
        {
            return View();
        }
    }
}

Course.dashboard/Controllers/MVC/BookController.cs
using Course.Repository.ViewModeles;
using Course.Service.IServices;
using Microsoft.AspNetCore.Mvc;
using NToastNotify;

namespace Course.dashboard.Controllers.MVC {
    public class BookController : Controller {
        private readonly IBookService _bookService;
        private readonly IToastNotification _toast;
        public BookController(IBookService bookService, IToastNotification toast)
        {
            _bookService = bookService;
            _toast = toast;
        }
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            return View();
        }
        [HttpPost]
        public JsonResult GetAll(int CurrentPage,int PageSize)
        {
            return Json(_bookService.GetAllAsync(CurrentPage,PageSize).Result);
        }
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(BookFormViewModel model)
        {
            if (!ModelState.IsValid)
            {
                _toast.AddErrorToastMessage("Data is inCorrect");
                return View(model);
            }
            if(await _bookService.CreateAsync(model))
            {
                _toast.AddSuccessToastMessage("Done");
                return RedirectToAction(nameof(Index));
            }
            return View(model);     
            
        }
    }
}

Course.dashboard/Controllers/MVC/CourseController.cs
using Course.Domain.Domains;
using Course.Repository.ViewModeles;
using Course.Service.IServices;
using Course.Service.Services;
using Microsoft.AspNetCore.Mvc;
using NToastNotify;

namespace Course.dashboard.Controllers.MVC {
    public class CourseController : Controller {
        private readonly ITitleService _titleService;
        private readonly ICourseService _courseService;

        private readonly IToastNotification _toast;

        public CourseController(ITitleService titleService, IToastNotification toast, ICourseService courseService)
        {
            _titleService = titleService;
            _toast = toast;
            _courseService = courseService;
        }
        [HttpGet]
        public IActionResult Create()
        {
            var Course = new CourseViewModel()
            {
                course = new CourseFormViewModel(),
                Title = new TitleFormViewModel(),
                Titles = _titleService.GetAll().Result
            };
            return View(Course);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CourseViewModel model)
        {
            var result = _courseService.AddCourse(model).Result;
            if (result)
            {
                _toast.AddSuccessToastMessage("Done");
                return RedirectToAction(nameof(Coures), new { userName = model.UserName, Search = "", orderby = "", currentPage = 1 });
            }
            _toast.AddErrorToastMessage("Enter Data or Incorrect Data..");
            return RedirectToAction(nameof(Create));
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Title(TitleFormViewModel title)
        {
            if (ModelState.IsValid)
            {
                if (_titleService.Create(title).Result)
                {
                    _toast.AddSuccessToastMessage("Saving Data");
                    return RedirectToAction(nameof(Create));
                }
            }
            ModelState.AddModelError(string.Empty, "Incoorect Data");
            _toast.AddErrorToastMessage("Enter or Incorrect Data..");
            return RedirectToAction(nameof(Create));
        }

        public async Task<IActionResult> Coures(string userName, string Search = "", string orderby = "", int currentPage = 1)
        {
            var result = await _titleService.GetAllTitles(currentPage, userName, Search, orderby);
            return View(result);
        }
        [HttpGet]
        public async Task<IActionResult> UpdateTitle(int Id)
        {
            var TitleVM = await _titleService.GetTitleById(Id);
            return View(TitleVM);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateTitle(UpdateTitleViewModel model)
        {
            if (await _titleService.UpdateTitle(model))
            {
                _toast.AddSuccessToastMessage("Done");
                return RedirectToAction(nameof(Coures), new { userName = Request.Form["userName"], Search = "", orderby = "", currentPage = 1 });
            }
            ModelState.AddModelError(string.Empty, "Data is Invalid");
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> DeleteTitle(int Id, string username)
        {
            if (await _titleService.DeleteTitle(Id))
            {
                _toast.AddSuccessToastMessage("Done");
                return RedirectToAction(nameof(Coures), new { userName = username, Search = "", orderby = "", currentPage = 1 });
            }
            ModelState.AddModelError(string.Empty, "Data is Invalid");
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> GetVideosForTitle(int Id)
        {
            var result = await _courseService.GetAllVideosById(Id);
            return View(result);
        }
        [HttpGet]
        public async Task<IActionResult> DeleteVideo(int Id, int? TitleId)
        {
            if (await _courseService.DeleteVideo(Id))
            {
                _toast.AddSuccessToastMessage("Done");
                return RedirectToAction(nameof(GetVideosForTitle), new { Id = TitleId });
            }
            _toast.AddErrorToastMessage("Try in another Time");
            return RedirectToAction(nameof(GetVideosForTitle), new { Id = TitleId });
        }
        [HttpGet]
        public async Task<IActionResult> UpdateVideoById(int id)
        {
            var result = await _courseService.GetVideoById(id);
            return View(result);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateVideoById(VideoByIdViewModel model)
        {
            if (!ModelState.IsValid)
            {
                _toast.AddErrorToastMessage("Try in another Time");
                return RedirectToAction(nameof(GetVideosForTitle), new { Id = model.TitleId });
            }
            var result = await _courseService.UpdateVideo(model);
            if (!result)
            {
                _toast.AddErrorToastMessage("Try in another Time");
                return RedirectToAction(nameof(GetVideosForTitle), new { Id = model.TitleId });
            }
            _toast.AddSuccessToastMessage("Done");
            return RedirectToAction(nameof(GetVideosForTitle), new { Id = model.TitleId });
        }
        [HttpPost]
        public async Task<JsonResult> GetVideos(int Id,int CurrentPage, int PageSize)
        {
            return Json(await _courseService.GetAllVideosJsonById(Id,CurrentPage,PageSize));
        }

    }
}

Course.dashboard/Controllers/MVC/HomeController.cs
using Course.Service.IServices;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Course.dashboard.Controllers.MVC
{
    public class HomeController : Controller
    {
        private readonly IHomeService _homeService;

        public HomeController(IHomeService homeService)
        {
            _homeService = homeService;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _homeService.Index()) ;
        }

    }
}

Course.dashboard/Areas/UI/Views/Home/AboutUs.cshtml
@model IEnumerable<ProfessorInfoViewModel>
@{
	ViewData["Title"] = "About Us";
}


<!-- breadcrumbs -->
<div class="breadcrumbs">
	<div class="container">
		<ol class="breadcrumb breadcrumb1 animated wow slideInLeft" data-wow-delay=".5s">
			<li><a asp-area="UI" asp-controller="Home" asp-action="Index"><span class="glyphicon glyphicon-home" aria-hidden="true"></span>Home</a></li>
			<li class="active">About </li>
		</ol>
	</div>
</div>
<!-- //breadcrumbs -->
<!-- about -->
<div class="about">
	<div class="container">
		<h3 class="w3_agile_header">About Us</h3>
		<div class="about-agileinfo w3layouts">
			<div class="col-md-8 about-wthree-grids grid-top">
				<h4>Unlocking Knowledge: Explore Our Comprehensive Courses System Today! </h4>
				<p class="top">Welcome to our state-of-the-art Course System, where knowledge meets innovation. Our platform offers a wide range of courses designed to empower you with the skills and expertise you need to excel in your chosen field.</p>
				<p>Whether you're a student looking to expand your horizons, a professional aiming to advance your career, or simply someone passionate about learning, our Courses System is your gateway to comprehensive, interactive, and engaging educational experiences. Explore our diverse catalog of courses, learn from top instructors, and embark on a journey of continuous learning and personal growth. Join us today and take the first step towards realizing your educational and career goals.</p>
			</div>
			<div class="col-md-4 about-wthree-grids">
				<div class="offic-time">
					<div class="time-top">
						<h4>Take It  :</h4>
					</div>
					<div class="time-bottom">
						<h5>But we accuse </h5>
						<h5> the most honorable.</h5>
						<p>But we accuse and in the right hatred we lead those who accuse </p>
					</div>
				</div>
	
			</div>
			<div class="clearfix"> </div>
		</div>
	</div>
</div>
<!-- //about -->
<!-- about-slid -->

<!-- //about-slid -->
<!-- about-team -->
@if (Model.Any())
{
	<div class="about-team">
		<div class="container">
			<h3 class="w3_agile_header">Meet Our Team</h3>
			<div class="team-agileitsinfo">
				@foreach(var t in Model){
				<div class="col-md-3 about-team-grids">
						<img src="~/Images/Profile/@((String.IsNullOrEmpty(t.img)?"Profile.png":t.img))" alt="@t.Name" />
					<div class="team-w3lstext">
						<h4>@t.Name</h4>
						<p>@t.About.</p>
					</div>
					<div class="social-icons caption">
						<ul>
							<li><a href="@t.Facebook" class="fa fa-facebook facebook"> </a></li>
							<li><a href="@t.Twitter" class="fa fa-twitter twitter"> </a></li>
							<li><a href="@t.LinkedIn" class="fa fa-linkedin linkedin"> </a></li>
								<li><a href="@t.Instagram" class="fa fa-instagram instagram"> </a></li>
						</ul>
						<div class="clearfix"> </div>
					</div>
				</div>
				}
				<div class="clearfix"> </div>
			</div>
		</div>
	</div>
}
<!-- //about-team -->
<!-- //footer -->
<div class="footer">
	<div class="container">
		<div class="w3_footer_grids">
			<div class="col-md-3 w3_footer_grid">
				<h3>Contact</h3>

				<ul class="address">
					<li><i class="glyphicon glyphicon-map-marker" aria-hidden="true"></i>Ashmone,Cairo,  <span>Egypt.</span></li>
					<li><i class="glyphicon glyphicon-envelope" aria-hidden="true"></i><a href="mailto:info@example.com">info@example.com</a></li>
					<li><i class="glyphicon glyphicon-earphone" aria-hidden="true"></i>+011 -212 - 37 - 611</li>
				</ul>
			</div>
			<div class="col-md-3 w3_footer_grid">
				<h3>Information</h3>
				<ul class="info">
					<li><i class="fa fa-arrow-right" aria-hidden="true"></i><a asp-area="UI" asp-controller="Home" asp-action="AboutUs">About Us</a></li>
					<li><i class="fa fa-arrow-right" aria-hidden="true"></i><a asp-area="UI" asp-controller="Auth" asp-action="ContactUs">Contact Us</a></li>

					<li><i class="fa fa-arrow-right" aria-hidden="true"></i><a asp-area="UI" asp-controller="Course" asp-action="Gourmet">Special Products</a></li>
				</ul>
			</div>
			<div class="col-md-3 w3_footer_grid">
				<h3>Category</h3>
				<ul class="info">
					<li><i class="fa fa-arrow-right" aria-hidden="true"></i><a asp-area="UI" asp-controller="Course" asp-action="Gourmet">Courses</a></li>
					<li><i class="fa fa-arrow-right" aria-hidden="true"></i><a asp-area="UI" asp-controller="Book" asp-action="Index">Books</a></li>
					<li><i class="fa fa-arrow-right" aria-hidden="true"></i><a href="#Instructor">Our Instructor</a></li>

				</ul>
			</div>
			<div class="col-md-3 w3_footer_grid">
				<h3>Profile</h3>
				<ul class="info">
					<li><i class="fa fa-arrow-right" aria-hidden="true"></i><a asp-area="UI" asp-controller="Cart" asp-action="Checkout">My Cart</a></li>
					<li><i class="fa fa-arrow-right" aria-hidden="true"></i><a asp-area="UI" asp-controller="Auth" asp-action="Login">Login</a></li>
					<li><i class="fa fa-arrow-right" aria-hidden="true"></i><a asp-area="UI" asp-controller="Auth" asp-action="Register">Create Account</a></li>

				</ul>
			</div>
			<div class="clearfix"> </div>
		</div>
	</div>


</div>